# GitHub Pages par static site deploy karne ke liye simple workflow
name: Deploy to GitHub Pages

on:
  # 'main' branch par push hone par yeh run hoga
  push:
    branches: ["main"]

  # Aapko Actions tab se manually run karne ki anumati deta hai
  workflow_dispatch:

# GitHub Pages par deploy karne ke liye GITHUB_TOKEN ko permission deta hai
permissions:
  contents: read
  pages: write
  id-token: write

# Ek samay mein sirf ek deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # 'build' directory ko upload karein
          path: './build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4